name: Tests

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GEOS
      run: |
        sudo apt update
        sudo apt install -y libgeos-dev

    - name: Configure CMake for tests
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build build

    - name: Run the executable
      id: run-executable
      run: echo "::set-output name=serialized::$(./build/app)"

    - name: Fail if output is not as expected
      if: steps.run-executable.outputs.serialized != '[2@2012-01-01T00:00:00+0000, 1@2012-01-02T00:00:00+0000, 4@2012-01-03T00:00:00+0000, 3@2012-01-04T00:00:00+0000)'
      run: exit 1
